# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_policy_engine.api.decision_matrix_api import DecisionMatrixApi


class TestDecisionMatrixApi(unittest.TestCase):
    """DecisionMatrixApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DecisionMatrixApi()

    def tearDown(self) -> None:
        pass

    def test_get_decision_matrix_api_v1_decision_matrix_get(self) -> None:
        """Test case for get_decision_matrix_api_v1_decision_matrix_get

        Get decision matrix
        """
        pass


if __name__ == '__main__':
    unittest.main()
