# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_policy_engine.api.opa_management_api import OPAManagementApi


class TestOPAManagementApi(unittest.TestCase):
    """OPAManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OPAManagementApi()

    def tearDown(self) -> None:
        pass

    def test_delete_opa_policy_api_v1_opa_policies_policy_id_delete(self) -> None:
        """Test case for delete_opa_policy_api_v1_opa_policies_policy_id_delete

        Delete OPA policy
        """
        pass

    def test_list_opa_policies_api_v1_opa_policies_get(self) -> None:
        """Test case for list_opa_policies_api_v1_opa_policies_get

        List OPA policies
        """
        pass

    def test_opa_health_api_v1_opa_health_get(self) -> None:
        """Test case for opa_health_api_v1_opa_health_get

        OPA health
        """
        pass


if __name__ == '__main__':
    unittest.main()
