# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_policy_engine.api.rules_api import RulesApi


class TestRulesApi(unittest.TestCase):
    """RulesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RulesApi()

    def tearDown(self) -> None:
        pass

    def test_create_rule_api_v1_rules_post(self) -> None:
        """Test case for create_rule_api_v1_rules_post

        Create rule
        """
        pass

    def test_delete_rule_api_v1_rules_rule_id_delete(self) -> None:
        """Test case for delete_rule_api_v1_rules_rule_id_delete

        Delete rule
        """
        pass

    def test_export_rego_api_v1_rules_export_rego_get(self) -> None:
        """Test case for export_rego_api_v1_rules_export_rego_get

        Export generated Rego policy
        """
        pass

    def test_export_rules_api_v1_rules_export_json_get(self) -> None:
        """Test case for export_rules_api_v1_rules_export_json_get

        Export all rules
        """
        pass

    def test_export_rules_csv_api_v1_rules_export_csv_get(self) -> None:
        """Test case for export_rules_csv_api_v1_rules_export_csv_get

        Export rules as CSV
        """
        pass

    def test_get_rule_api_v1_rules_rule_id_get(self) -> None:
        """Test case for get_rule_api_v1_rules_rule_id_get

        Get rule
        """
        pass

    def test_get_rules_meta_api_v1_rules_meta_get(self) -> None:
        """Test case for get_rules_meta_api_v1_rules_meta_get

        All rule metadata
        """
        pass

    def test_import_rules_api_v1_rules_import_json_post(self) -> None:
        """Test case for import_rules_api_v1_rules_import_json_post

        Import rules from JSON
        """
        pass

    def test_import_rules_csv_api_v1_rules_import_csv_post(self) -> None:
        """Test case for import_rules_csv_api_v1_rules_import_csv_post

        Import rules from CSV
        """
        pass

    def test_list_known_permissions_api_v1_rules_meta_permissions_get(self) -> None:
        """Test case for list_known_permissions_api_v1_rules_meta_permissions_get

        List known permissions
        """
        pass

    def test_list_known_roles_api_v1_rules_meta_roles_get(self) -> None:
        """Test case for list_known_roles_api_v1_rules_meta_roles_get

        List known roles
        """
        pass

    def test_list_rules_api_v1_rules_get(self) -> None:
        """Test case for list_rules_api_v1_rules_get

        List rules
        """
        pass

    def test_toggle_rule_api_v1_rules_rule_id_toggle_patch(self) -> None:
        """Test case for toggle_rule_api_v1_rules_rule_id_toggle_patch

        Toggle rule
        """
        pass

    def test_update_rule_api_v1_rules_rule_id_put(self) -> None:
        """Test case for update_rule_api_v1_rules_rule_id_put

        Update rule
        """
        pass


if __name__ == '__main__':
    unittest.main()
