# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_policy_engine.api.database_api import DatabaseApi


class TestDatabaseApi(unittest.TestCase):
    """DatabaseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DatabaseApi()

    def tearDown(self) -> None:
        pass

    def test_browse_deploy_history_api_v1_db_tables_deploy_history_get(self) -> None:
        """Test case for browse_deploy_history_api_v1_db_tables_deploy_history_get

        Browse deploy history table
        """
        pass

    def test_browse_metadata_api_v1_db_tables_metadata_get(self) -> None:
        """Test case for browse_metadata_api_v1_db_tables_metadata_get

        Browse metadata table
        """
        pass

    def test_browse_rules_api_v1_db_tables_rules_get(self) -> None:
        """Test case for browse_rules_api_v1_db_tables_rules_get

        Browse rules table
        """
        pass

    def test_db_stats_api_v1_db_stats_get(self) -> None:
        """Test case for db_stats_api_v1_db_stats_get

        Database statistics
        """
        pass

    def test_run_query_api_v1_db_query_post(self) -> None:
        """Test case for run_query_api_v1_db_query_post

        Run read-only SQL query
        """
        pass


if __name__ == '__main__':
    unittest.main()
