# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ds_policy_engine.models.import_request import ImportRequest

class TestImportRequest(unittest.TestCase):
    """ImportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImportRequest:
        """Test ImportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImportRequest`
        """
        model = ImportRequest()
        if include_optional:
            return ImportRequest(
                rules = [
                    {
                        'key' : null
                        }
                    ],
                mode = 'merge'
            )
        else:
            return ImportRequest(
                rules = [
                    {
                        'key' : null
                        }
                    ],
        )
        """

    def testImportRequest(self):
        """Test ImportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
