"""
Rego policy generation service.

Uses strategy pattern — swap the generation strategy to switch
between permission-based, RBAC, or ABAC approaches within OPA.
"""

import json
import logging
from typing import Protocol

logger = logging.getLogger("policy_engine.rego_generator")


class RegoGenerationStrategy(Protocol):
    """Protocol defining the interface for Rego generation strategies.

    Implementations convert a list of rule dictionaries into valid Rego source
    code that can be pushed to a policy engine such as OPA.
    """

    def generate(self, rules: list[dict]) -> str:
        """Generate Rego source code from a list of rules.

        Args:
            rules: List of rule dictionaries. Each dict is expected to contain
                keys such as ``name``, ``role``, ``permissions``, and ``enabled``.

        Returns:
            str: Valid Rego source code ready to be pushed to the policy engine.
        """
        ...


class PermissionBasedRegoStrategy:
    """
    Current strategy: role + institute permission resolution.

    Generates Rego that maps (role, institute) -> list of permissions.
    Each rule becomes a decision assignment in Rego.
    """

    def generate(self, rules: list[dict]) -> str:
        """Generate Rego source that maps each role to its granted permissions.

        Enabled rules produce ``decision`` assignments keyed on ``input.role``.
        Disabled rules are emitted as comments for traceability.

        Args:
            rules: List of rule dictionaries with keys ``name``, ``role``,
                ``permissions``, and ``enabled``.

        Returns:
            str: Rego source code under the ``ds.authz`` package.
        """
        enabled = [r for r in rules if r.get("enabled", True)]
        disabled = len(rules) - len(enabled)
        logger.debug("Generating Rego: %d rules (%d enabled, %d disabled)", len(rules), len(enabled), disabled)

        lines = [
            "package ds.authz",
            "",
            "# Auto-generated by Policy Engine",
            "",
            "import rego.v1",
            "",
            "default decision := {",
            '    "permissions": []',
            "}",
            "",
        ]

        for rule in rules:
            if not rule.get("enabled", True):
                lines.append(f"# [DISABLED] {rule.get('name', 'unnamed')}")
                lines.append("")
                continue

            perms = json.dumps(rule.get("permissions", []))
            name = rule.get("name", "unnamed")
            role = rule.get("role", "")
            institute = rule.get("institute", "")

            lines.append(f"# {name}")
            lines.append("decision := {")
            lines.append(f'    "permissions": {perms}')
            lines.append("} if {")

            if role:
                lines.append(f'    input.role == "{role}"')
            if institute:
                lines.append(f'    input.institute == "{institute}"')

            lines.append("}")
            lines.append("")

        return "\n".join(lines)


class RbacRegoStrategy:
    """Future strategy: hierarchical RBAC with role inheritance.

    This is a placeholder for when the team wants to adopt full RBAC with
    role hierarchies and permission inheritance. To activate, change
    ``get_rego_strategy()`` in ``dependencies.py`` to return an instance
    of this class.

    Role inheritance means a parent role (e.g. ``admin``) automatically
    inherits all permissions from its child roles (e.g. ``editor``,
    ``viewer``), eliminating the need to duplicate permission lists.
    """

    def generate(self, rules: list[dict]) -> str:
        """Generate hierarchical RBAC Rego source from rules.

        Args:
            rules: List of rule dictionaries defining role hierarchies
                and permissions.

        Returns:
            str: Rego source code implementing hierarchical RBAC.

        Raises:
            NotImplementedError: Always, as this strategy is not yet implemented.
        """
        # TODO: Implement hierarchical RBAC generation
        raise NotImplementedError("RBAC strategy not yet implemented")


# Default strategy instance
default_rego_strategy = PermissionBasedRegoStrategy()
