"""
Unit tests for the Rego generation service.

Tests that the generated Rego source code is syntactically correct
and contains the expected rules, conditions, and permissions.
"""

import pytest

from app.services.rego_generator import PermissionBasedRegoStrategy


@pytest.fixture
def strategy():
    return PermissionBasedRegoStrategy()


@pytest.fixture
def sample_rules():
    return [
        {
            "id": "rule-1",
            "name": "Owner Full",
            "role": "catalog_owner",
            "permissions": ["catalog:read", "catalog:create", "decentralized-search:execute"],
            "enabled": True,
        },
        {
            "id": "rule-2",
            "name": "Consumer Read",
            "role": "catalog_consumer",
            "permissions": ["catalog:read"],
            "enabled": True,
        },
    ]


class TestPermissionBasedRegoStrategy:
    """Tests for the permission-based Rego generation strategy."""

    def test_generates_valid_rego_package(self, strategy, sample_rules):
        """Verify that generated Rego contains the ds.authz package declaration."""
        rego = strategy.generate(sample_rules)
        assert "package ds.authz" in rego

    def test_generates_import_statement(self, strategy, sample_rules):
        """Verify that generated Rego includes the rego.v1 import."""
        rego = strategy.generate(sample_rules)
        assert "import rego.v1" in rego

    def test_generates_default_decision(self, strategy, sample_rules):
        """Verify that generated Rego has a default decision with empty permissions."""
        rego = strategy.generate(sample_rules)
        assert "default decision := {" in rego
        assert '"permissions": []' in rego

    def test_generates_role_condition(self, strategy, sample_rules):
        """Verify that generated Rego contains role conditions for each rule."""
        rego = strategy.generate(sample_rules)
        assert 'input.role == "catalog_owner"' in rego
        assert 'input.role == "catalog_consumer"' in rego

    def test_generates_permissions_array(self, strategy, sample_rules):
        """Verify that all permissions from the rules appear in the Rego output."""
        rego = strategy.generate(sample_rules)
        assert '"catalog:read"' in rego
        assert '"catalog:create"' in rego
        assert '"decentralized-search:execute"' in rego

    def test_generates_rule_comments(self, strategy, sample_rules):
        """Verify that each rule's name appears as a comment in the Rego output."""
        rego = strategy.generate(sample_rules)
        assert "# Owner Full" in rego
        assert "# Consumer Read" in rego

    def test_disabled_rules_are_commented(self, strategy):
        """Verify that disabled rules appear as comments and not as active Rego rules."""
        rules = [
            {
                "id": "r1",
                "name": "Disabled Rule",
                "role": "catalog_owner",
                "permissions": ["catalog:read"],
                "enabled": False,
            },
        ]
        rego = strategy.generate(rules)
        assert "[DISABLED] Disabled Rule" in rego
        assert 'input.role == "catalog_owner"' not in rego

    def test_empty_rules_generates_default_only(self, strategy):
        """Verify that an empty rules list generates only the default decision block."""
        rego = strategy.generate([])
        assert "package ds.authz" in rego
        assert "default decision := {" in rego
        # Should not have any role-based rules
        assert "input.role ==" not in rego

    def test_generates_decision_block_per_enabled_rule(self, strategy, sample_rules):
        """Verify that each enabled rule produces its own decision block."""
        rego = strategy.generate(sample_rules)
        # Count "decision := {" occurrences (excluding default)
        lines = rego.split("\n")
        decision_lines = [
            line
            for line in lines
            if line.strip().startswith("decision := {") and "default" not in line
        ]
        assert len(decision_lines) == 2

    def test_auto_generated_comment_present(self, strategy, sample_rules):
        """Verify that the Rego output contains the auto-generated header comment."""
        rego = strategy.generate(sample_rules)
        assert "Auto-generated by Policy Engine" in rego

    def test_mixed_enabled_disabled(self, strategy):
        """Verify that only enabled rules produce active Rego; disabled are commented out."""
        rules = [
            {
                "id": "r1",
                "name": "Active",
                "role": "catalog_owner",
                "permissions": ["catalog:read"],
                "enabled": True,
            },
            {
                "id": "r2",
                "name": "Inactive",
                "role": "catalog_creator",
                "permissions": ["catalog:read"],
                "enabled": False,
            },
            {
                "id": "r3",
                "name": "Also Active",
                "role": "catalog_consumer",
                "permissions": ["catalog:read"],
                "enabled": True,
            },
        ]
        rego = strategy.generate(rules)
        assert 'input.role == "catalog_owner"' in rego
        assert 'input.role == "catalog_creator"' not in rego
        assert 'input.role == "catalog_consumer"' in rego
        assert "[DISABLED] Inactive" in rego
