# coding: utf-8

"""
    Data Space Policy Engine Service

    Standalone policy-as-code microservice. Evaluates user permissions based on role and institute using OPA.

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class RuleCreate(BaseModel):
    """
    Schema for creating a new authorization rule.  Defines the required and optional fields accepted when a client submits a request to create a rule. Each rule maps a role to a set of permissions.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=100)] = Field(description="Rule display name")
    description: Optional[Annotated[str, Field(strict=True, max_length=500)]] = ''
    role: StrictStr = Field(description="Target role for this rule")
    institute: Optional[StrictStr] = Field(default='', description="Institute this rule applies to")
    permissions: Optional[List[StrictStr]] = Field(default=None, description="Permissions granted by this rule. May be empty (the service surfaces such rules as a warning in the overview).")
    enabled: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["name", "description", "role", "institute", "permissions", "enabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description") if obj.get("description") is not None else '',
            "role": obj.get("role"),
            "institute": obj.get("institute") if obj.get("institute") is not None else '',
            "permissions": obj.get("permissions"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True
        })
        return _obj


