apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds-policy-engine.fullname" . }}
  namespace: {{ include "ds-policy-engine.namespace" . }}
  labels:
    {{- include "ds-policy-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ds-policy-engine.selectorLabels" . | nindent 4 }}
